./build/bin/geth \
    --gcmode archive \
    --syncmode snap \
    --datadir ~/taiko/taiko_datadir \
    --discovery.port 30303 \
    --nodiscover \
    --port 31303 \
    --networkid 167010 \
    --http \
    --http.port 8545 \
    --http.addr "0.0.0.0" \
    --http.vhosts "*" \
    --http.corsdomain "*" \
    --http.api eth,net,web3,txpool,miner,taiko,admin \
    --ws \
    --ws.port 18546 \
    --ws.addr "0.0.0.0" \
    --ws.origins "*" \
    --authrpc.addr "0.0.0.0" \
    --authrpc.port 18551 \
    --authrpc.vhosts "*" \
    --authrpc.jwtsecret ~/taiko/jwt.txt \
    --allow-insecure-unlock \
    --ws.api eth,net,web3,txpool,miner,taiko \
    --taiko \
    --maxpeers 100 \
    console 
